## makeCacheMatrix and cacheSolve convert a matrix into a format that allows for the
## caching of the solve() operation on that matrix in the event that the calculation
## needs to be performed a large number of times and the matrix values remain constant.


## makeCacheMatrix takes a matrix argument and creates a list containing 
## functions to do the following:
## set value of matrix, get value of matrix, set value of inverse, get value of inverse

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setsolve <- function(solve) m <<- solve
  getsolve <- function() m
  list(set = set, get = get,
       setsolve = setsolve,
       getsolve = getsolve)
}


## cacheSolve takes an argument of a list generated by the makeCacheMatrix function.
## It checks if the inverse has been previously calculated (checking whether or not  
## getsolve() of the argument object returns null). If it hasn't, the inverse is calculated,
## the result is cached in the argument object by calling the setsolve() function and returned.
## If it has, the cached solution is returned along with a message stating this.

cacheSolve <- function(x, ...) {
  m <- x$getsolve()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setsolve(m)
  m
}
